import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Home() {
  return (


    <div className={styles.container}>
      <style jsx>
        {
          `
            .myimg{
              border-radius:5px;
              margin-Top:25px;
            }
            main>h1{
              font-size:40px;
            }
            h1{
              font-size:25px;
            }

            `
        }
      </style>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
     

      <main className={styles.main}>

        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <img src="/bike.jpg" className='myimg' alt="" width={237} height={158} />
        <h1>Latest Blogs</h1>
        <p className={styles.description}>
          <span className='myspan'>
            A hunting blog for coders by a coder
          </span>

          {/* <h1>Popular Blogs</h1> */}
        </p>

        <div className='blogs'>

          <div className='blogitem'>

            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>
          <div className='blogitem'>
            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>
          <div className='blogitem'>
            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>
          <div className='blogitem'>
            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>

        </div>

      </main>


    </div>
  )
}
