import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Home() {
  return (


    <div className={styles.container}>
      <style jsx>
        {
          `
            .myimg{
              border-radius:92px;
              margin-Top:25px;
              max-width:175px;
              
            }
           .myh1{
             font-size:45px;
             font-weight:500;
           }
            h1{
              font-size:20px;
            }

            `
        }
      </style>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
     

      <main className={styles.main}>

        <h1 className='myh1'>
          Hunting Coder
        </h1>
        <img src="/bike.jpg" className='myimg' alt="" width={237} height={158} />
       
        <p className={styles.description}>
          
        <h1 className={styles.title}>Latest Blogs</h1>
          {/* <h1>Popular Blogs</h1> */}
        </p>
        <span className={styles.description}>
                    A hunting blog for coders by a coderdjlfjljdlf
                    aldjfljdljfjdf ljladfljdjfljdlf ljljdljfljdlfjldkjf
                    jdlfjjdfljdlfj
                  </span>
        <div className={styles.blog}>

          <div className='blogitem'>

            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>
          <div className='blogitem'>
            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>
          <div className='blogitem'>
            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>
          <div className='blogitem'>
            <h1>How to learn javascript in 2022</h1>
            <p>javascript is the language to design logic for the web</p>
          </div>

        </div>

      </main>


    </div>
  )
}
